### ISSUE TITLE
Crash with Sodium Dynamic Lights 1.0.0 (Forge 1.20.1)

### ISSUE THREAD

**Issue by katubug** [txnimc/SodiumDynamicLights#1]
Hi, I just updated from Dynamic Lights Reforged 1.6.0 to Sodium Dynamic Lights 1.0.0 and got this crash on loading my singleplayer world in a modded instance:

[crash-2024-09-02_08.15.01-client.txt](https://github.com/user-attachments/files/16839166/crash-2024-09-02_08.15.01-client.txt)

**Comment by nthxny** [comment]
@katubug can you post your full log file?

**Comment by nthxny** [comment]
nvm, I found the problem, will be fixed today

**Comment by katubug** [comment]
Oh okay, sweet, thank you!
