### ISSUE TITLE
[Bug] Ticking Entity Error

### ISSUE THREAD

**Issue by Cyranos** [txnimc/SodiumDynamicLights#11]
To note I am not certain is actually ticking entity, though the first crash log I got was for the local player; [here](https://mclo.gs/NCqbiKa) and the second one I got was for a bat entity apparently; [here](https://mclo.gs/3qxoddT)

**Comment by muon-rw** [comment]
Caused by Ars Nouveau

**Comment by nthxny** [comment]
should be fixed in latest update.
