### ISSUE TITLE
Dynamic Lights tab not appearing

### ISSUE THREAD

**Issue by SoundCrafterYT** [txnimc/SodiumDynamicLights#12]
I just installed this mod, and the tab is not there when I click on Video Settings!
![image](https://github.com/user-attachments/assets/7dacb523-49bd-4970-9eaf-533c3dc53191)

Any tips on how to fix this problem?

**Comment by AronGt** [comment]
Me ocurre lo mismo. Lamento decir que no encontré ninguna posible solución.
