### ISSUE TITLE
Newer Versions do not work with Radiant Gear

### ISSUE THREAD

**Issue by Sazuzaki** [txnimc/SodiumDynamicLights#13]
Hello, the newer versions of this mod do not work with Radiant Gear, whereas previous versions do.

The last known version to work with Radiant Gear is version 1.60 from 9/1/2023.

**Comment by raffle2** [comment]
Same problem here on forge 47.3.0 1.20.1: https://www.curseforge.com/minecraft/mc-mods/radiant-gear

**Comment by nthxny** [comment]
the old version is very out of date with upstream LambDynLights, so the API has changed. Any mod supporting the old API will need to be updated to support the new one
