### ISSUE TITLE
Forge Config API Port is not listed as dependency

### ISSUE THREAD

**Issue by Rafii2198** [txnimc/SodiumDynamicLights#14]
In the dependencies, Forge Config API Port is not listed, yet without the game will crash with a mixin error https://mclo.gs/Lsiy2Au
Tested on Fabric only with only Sodium, Fabric API and Sodium Dynamic Lights installed, as a proof here is another log with the game loaded and only that mod was added https://mclo.gs/gh2PyWh

**Comment by nthxny** [comment]
Idk what you're doing here but it probably has something to do with the fact that your logs say "[✘] Forge Config API Port.jar (disabled)"

FCAPI port is jarjar'd into the mod. You probably added it manually and disabled it somehow.

**Comment by Rafii2198** [comment]
@nthxny that is just prism launcher saying that it is disabled. If you ran the mod with just Sodium, the mod and FAPI the game will crash before launching

**Comment by nthxny** [comment]
it does not. You are doing something wrong.

**Comment by Rafii2198** [comment]
I literally send you proof it is crashing, what else do you want?
