### ISSUE TITLE
(1.21.1) Still crashing on the latest version

### ISSUE THREAD

**Issue by BugmanBugman** [txnimc/SodiumDynamicLights#16]
https://gist.github.com/BugmanBugman/abfccd8307f55edc6b789dd7e1ad7ad7

**Comment by BugmanBugman** [comment]
Any update on this? Not sure what could be causing it this time

**Comment by txnitxnichopper** [comment]
Can't seem to reproduce this with just this mod, loads fine on 1.21.1 NeoForge for me. You'll have to link your modlist or pack zip for me to debug this
