### ISSUE TITLE
[1.21.1] Crashing with 1.0.1 with Sodium

### ISSUE THREAD

**Issue by BugmanBugman** [txnimc/SodiumDynamicLights#2]
[BugmanBugman](https://gist.github.com/BugmanBugman/f3eb6f69719adde8a85d8b27ff4efa16)

**Comment by Felix14-v2** [comment]
Sodium 0.6.0 beta-1 is still unsupported I guess

**Comment by nthxny** [comment]
a bad 1.21 build went out on Curse when I ported the project to 1.20, the prior version works fine. Will fix for future releases
