### ISSUE TITLE
Extreme FPS drops when Magma Slimes and Blazes move around

### ISSUE THREAD

**Issue by DemiVFX** [txnimc/SodiumDynamicLights#23]
Hi,

I apologize if this issue is somehow submitted incorrectly, I've never used github before.

I'm working on a modpack for my friends and found that I was dropping from 120fps to 4fps when going near some structures. I found out that it wasn't the structures themselves causing this lag, but the amount of magma slimes and blazes that were spawning inside of it. I checked on vanilla and this lag did not exist, and spent a few hours narrowing down the modlist until I found the culprit, and it was unfortunately this mod. This mod was on (as far as I'm aware) default settings, and the mod that generated the structures/spawners where I noticed heavy amounts of lag was When Dungeons Arise.

I'm submitting this before I forget, but I'm going to try now to refine the settings and see if I can clear up the lag and still keep the mod working.

Thank you!

**Comment by DemiVFX** [comment]
I'd like to append to this that disabling dynamic entity lighting in the settings solved these massive fps issues for me!

**Comment by txnitxnichopper** [comment]
There's not much of a way around this unfortunately but I think dynamic entity lighting should maybe be off by default for this reason. I might push an update to do that. 

There is basically zero impact with just the player holding a torch, but lighting updates for hundreds of entities can be expensive

**Comment by DemiVFX** [comment]
Disabling it by default would have saved modding noob me a lot of frustration, might be worth trying! I've noticed a lot of people seemed to be having similar issues with the same WDA structures so I wouldn't be surprised if they were experiencing the same issue on their own installs. I should probably leave a comment on WDA's page to let the mod author know.

**Comment by txnitxnichopper** [comment]
Should be fixed in latest release.
