### ISSUE TITLE
Remove Xenon from Dependencies on Curseforge

### ISSUE THREAD

**Issue by ambientNexus** [txnimc/SodiumDynamicLights#3]
Xenon has been abandoned for nearly 6 months due to Sodium releasing an official neoforge build, and Embeddium is still under active development for 1.20 onwards. It'll only cause confusion for people already using Embeddium or Sodium to keep the 'required' dependency for xenon, even though the mod works perfectly fine with both Sodium and Embeddium.

**Comment by nthxny** [comment]
Xenon is not required. Curseforge does not have a way to mark two dependencies and have you select which one, so I just chose Xenon. 

The only problem here is that maybe Xenon should throw a better error when you install it alongside Embeddium on accident

The last update for Xenon was also 3 months ago, and nothing major has released on the Embeddium side to require an update. Luna Pixel is still using it in all their packs, and that's what it was originally made for.
