### ISSUE TITLE
Crash on 1.20.1 Forge

### ISSUE THREAD

**Issue by Looodon** [txnimc/SodiumDynamicLights#4]
Hey,
I'm getting a crash with this mod because it requires xenon, which clashes with [embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium) giving this crash report:
https://pastebin.com/bDPudgyh

After I remove embeddium It launched the game I went and installed "Sodium/Embeddium Extras" which causes this crash log below because it forces me: 
https://pastebin.com/GttTJ8JF

and this:
![Screen Shot (2024-09-02 14_47_15)](https://github.com/user-attachments/assets/9fb73e93-1315-4b10-a0f0-496b92c43f78)

**Comment by nthxny** [comment]
Xenon is only needed if you don't have Embeddium. You can choose one or the other. Just remove Xenon if you wanna use Embeddium
