### ISSUE TITLE
1.20.1 Crash

### ISSUE THREAD

**Issue by tgstyle** [txnimc/SodiumDynamicLights#6]
[crash-2024-09-06_13.51.48-client.txt](https://github.com/user-attachments/files/16912456/crash-2024-09-06_13.51.48-client.txt)

**Comment by serioos** [comment]
I have this crash too. Had to downgrade.

[crash-2024-09-06_13.53.24-client.txt](https://github.com/user-attachments/files/16914260/crash-2024-09-06_13.53.24-client.txt)

Minecraft 1.20.1
Forge 47.3.7
sodiumdynamiclights-forge-1.0.1-1.20.1.jar

**Comment by nthxny** [comment]
this is an incompat with Ars, will be fixed soon

**Comment by JaredCCCVIII** [comment]
i can't upgrade this mod because of the crash

**Comment by Camawama** [comment]
> this is an incompat with Ars, will be fixed soon

can't wait for the update :D

**Comment by nthxny** [comment]
should be fixed in latest update.
