### ISSUE TITLE
Improper Smooth Lighting with dynamic light equipped

### ISSUE THREAD

**Issue by Barerock** [txnimc/SodiumDynamicLights#7]
![2024-09-08_18 48 31](https://github.com/user-attachments/assets/fca37236-ddc5-4c3d-b60f-6a6906d4b78e)
![2024-09-08_18 48 35](https://github.com/user-attachments/assets/b4ddb01f-5d93-46f3-99e1-e4de4c2624b3)

Shadowed image is a couple blocks closer.
Issue not present when light is unequipped, I have a lantern in my curios slot, but it occurs with handheld lights too.

Embeddium 0.3.31
DL forge 1.0.2
Forge 47.3.5
MC 1.20.1

**Comment by nthxny** [comment]
I have no clue what you are talking about. If this is supposed to be a before and after, they look exactly the same.

**Comment by Barerock** [comment]
They do not, why would you not wait for me to respond!? The second image displays dark edges, which appear on blocks at floor level.

**Comment by Barerock** [comment]
This is verifiable in multiple mod instances with any number of mods. As long as dynamic lights is present this issue occurs where distance leads to awkward smooth lighting and shadows.

**Comment by nthxny** [comment]
yeah I still don't know what you're talking about.

**Comment by Barerock** [comment]
What is that supposed to mean. Do you need more details or do you just not believe that I've tested this in numerous settings. It's much more glaring ingame than in screenshot. The smooth lighting pops in and out instantly, so it becomes annoying. Maybe lower your screen brightness. Those two images are obviously different to my eyes.

**Comment by nthxny** [comment]
are you complaining about the update rate?

**Comment by Barerock** [comment]
No. The update rate is not at all related to this. The smooth lighting breaks when close to interior walls, causing floor level shadows to appear and disappear instantly when walking around. I am not a shader dev, I have no idea about the internals. What I do know is that this was not an issue at some point and now is an issue.

**Comment by Barerock** [comment]
If you're not going to do anything about it just say so. Geez. This was an unpleasant interaction to say the least. I shouldn't have to explain a replicable bug over and over again to a dev and get "are you complaining" back. FFS I'm doing the testing FOR you and your best effort is blaming me for having an issue with YOUR mod.

If it's relevant (lol), this happens with multiple shaders, and wasn't an issue before 1.6.0 I think. I can't be sure, since Embeddium has also gone through numerous changes and broken smooth lighting for some things like water. I do know that having a dynamic light equipped will cause this, regardless of what kind it is, equipped via curios or equipped in hotbar.

I'm going to mow the lawn to not be frustrated anymore.

**Comment by nthxny** [comment]
again, your screenshots look exactly the same. I don't know what you're talking about from one picture. If this is an issue that happens when moving around, maybe send a video. 

I just booted up both this mod and the original LambDynamicLights and they both appear fine with no difference between the two.
