### ISSUE TITLE
1.20.1 Dedicated Server Not Working

### ISSUE THREAD

**Issue by dainekoichi** [txnimc/SodiumDynamicLights#8]
Dedicated server will not boot up with the mod enabled.
[2024-09-10-1.log](https://github.com/user-attachments/files/16941703/2024-09-10-1.log)

Crash also happens when I remove the JAR from the server side with the a similar error stack.

**Comment by Camawama** [comment]
It's a client sided mod. It's not required on the server and if you removed it, it's not the mod causing your crash. Sorry.
